project:
  type: book
  output-dir: .

language: language_custom.yml

book:
  title: Título de la tesis
  date: Düsseldorf, Abril 2024
  author:
    name: Nombre del autor
  downloads: [pdf]
  abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vel sapien et quam ultricies laoreet lobortis vel nisi. Nulla consectetur nisi non augue accumsan lobortis. Praesent eu nibh vel risus rutrum laoreet a eget sem. Integer sodales mi ut lacus condimentum, non tristique nibh tincidunt. Fusce blandit eu purus eget ultrices. Duis feugiat non quam in vestibulum. In nec lacus dictum, ullamcorper dui semper, euismod purus. Aenean pellentesque ultrices tincidunt. Aliquam placerat metus ut sollicitudin pharetra. Suspendisse aliquet augue quis elementum fermentum. Nullam eu sem leo. Proin placerat est tortor, et posuere felis volutpat eu. Donec pharetra diam mauris, in luctus augue dignissim id. Sed tincidunt commodo tincidunt."
  chapters:
    - index.qmd
    - Chapters/Chapter2.qmd
    - references.qmd
  appendices: 
    - Appendices/ApendiceA.qmd

  site-url: https://nmfs-opensci.github.io/quarto-thesis/
  repo-url: https://github.com/nmfs-opensci/quarto-thesis
  repo-actions: [edit, source, issue]
  search: true



thesis:
  supervisor: 
    name: Nombre del supervisor
  degree-name: Ingeniero
  university: Universidad Gotitas del Saber
  department: Departamento de Ciencias de la Vida
  group: Laboratorio de Microbiología Ambiental
  faculty: Facultad de Ingeniería en Biotecnología 
  declaration: "Frontmatter/declaration.tex"
  quotation:
    text: "There is no such thing as a free lunch"
    attribution: Milton Friedman
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"
  # logo: images/logo.png
  logo-height: "3cm"

bibliography: [example.bib]
  
execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf:
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2

    


